/**
 * Bug condition exploration test — pool error / process-crash guards.
 *
 * Property 1: Bug Condition - Process Crashes on Pool Errors and Unguarded Exceptions
 *
 * This test MUST be written and run BEFORE any fix is implemented (Phase 1 of the bugfix
 * methodology). It is expected to demonstrate that the CURRENT (unfixed) `src/index.ts`:
 *
 *   (a) has no `pool.on('error', ...)` listener attached, so emitting `'error'` on the pool
 *       crashes the process (design.md `isBugCondition('pool_error_event')`), and
 *   (b) has no `process.on('uncaughtException'/'unhandledRejection', ...)` guard, so an
 *       uncaught throw or unhandled rejection also crashes the process
 *       (design.md `isBugCondition('uncaught_or_unhandled')`).
 *
 * Because the real crash must be observed (not swallowed by the vitest worker itself), each
 * scenario is exercised in an isolated child process via `child_process.spawnSync` against small
 * fixture scripts under `src/test/fixtures/`. This keeps the test harness stable regardless of
 * whether the injected error actually kills the process.
 *
 * Validates: Requirements 1.1, 1.5
 */
import { describe, test, expect, beforeAll } from 'vitest';
import fc from 'fast-check';
import { spawnSync } from 'child_process';
import * as path from 'path';
import * as fs from 'fs';
import { Pool } from 'pg';

const OPENSOURCE_ROOT = path.resolve(__dirname, '..');
const DIST_ENTRY = path.join(OPENSOURCE_ROOT, 'dist', 'index.js');
const POOL_ERROR_FIXTURE = path.join(__dirname, 'test', 'fixtures', 'pool-error-crash.fixture.cjs');
const UNCAUGHT_UNHANDLED_FIXTURE = path.join(
  __dirname,
  'test',
  'fixtures',
  'uncaught-unhandled-crash.fixture.cjs'
);

// Arbitrary for the injected error's message/code, per the task's "Scoped PBT Approach": we
// generate the error shape (message/code), not the trigger mechanism (which is fixed to the two
// concrete unfixed-code paths this task targets).
const injectedErrorArb = fc.record({
  message: fc.oneof(
    fc.constant('Connection terminated unexpectedly'),
    fc.constant('Connection terminated'),
    fc.constant('read ECONNRESET'),
    fc.string({ minLength: 1, maxLength: 60 })
  ),
  code: fc.option(
    fc.constantFrom('ECONNRESET', 'ECONNREFUSED', 'EPIPE', 'ETIMEDOUT'),
    { nil: undefined }
  ),
});

function runFixture(fixturePath: string, env: Record<string, string>) {
  return spawnSync(process.execPath, [fixturePath], {
    cwd: OPENSOURCE_ROOT,
    env: { ...process.env, ...env },
    encoding: 'utf-8',
    timeout: 10_000,
  });
}

describe('Bug condition exploration: pool error / process-crash guards (Property 1)', () => {
  beforeAll(() => {
    // These fixtures spawn `dist/index.js` (or mirror its Pool config) in a child process. If the
    // project hasn't been built yet, fail fast with an actionable message rather than a confusing
    // MODULE_NOT_FOUND deep in a child process.
    if (!fs.existsSync(DIST_ENTRY)) {
      throw new Error(
        `Expected build output at ${DIST_ENTRY} — run "npm run build" in opensource/ before running this test.`
      );
    }
  });

  describe('(a) pool.on(\'error\') listener is absent, so pool.emit(\'error\', ...) crashes the process', () => {
    test('hasPoolErrorListener(pool) is false for a pool built with the same config shape as ensureConnection()', () => {
      // Mirrors the config object passed to `new Pool(...)` inside `ensureConnection()`. No
      // `.connect()` is called, so no real database is contacted.
      const pool = new Pool({
        host: 'localhost',
        port: 5432,
        database: 'test',
        user: 'test',
        password: 'test',
        ssl: false,
      });

      expect(pool.listenerCount('error')).toBe(0);
    });

    test(
      'emitting pool "error" crashes the process today (counterexample: unfixed code has no listener)',
      () => {
        fc.assert(
          fc.property(injectedErrorArb, (injectedError) => {
            const result = runFixture(POOL_ERROR_FIXTURE, {
              INJECTED_ERROR: JSON.stringify(injectedError),
            });

            // Bug condition confirmation: no listener was attached before the emit...
            expect(result.stdout).toContain('LISTENER_COUNT_BEFORE_EMIT=0');
            // ...and the process crashed instead of surviving to print "SURVIVED".
            expect(result.status).not.toBe(0);
            expect(result.stdout).not.toContain('SURVIVED');
          }),
          { numRuns: 8 }
        );
      },
      20_000
    );
  });

  describe('(b) process-level uncaughtException/unhandledRejection guard now exists (Task 14.1 fix)', () => {
    // Connection-level error shapes: all of the concrete messages/codes generated by
    // `injectedErrorArb` above (aside from the catch-all random string case) are connection-level
    // per `isConnectionLevelError()` in src/index.ts.
    // NOTE: message variants here are restricted to phrases that `isConnectionLevelError()` in
    // src/index.ts recognizes on their own (via CONNECTION_LEVEL_ERROR_MESSAGE_PHRASES), since
    // `code` is optional (`fc.option(..., { nil: undefined })`) and may be omitted. A message
    // like 'read ECONNRESET' relies entirely on `error.code === 'ECONNRESET'` for
    // classification — pairing it with `code: undefined` produced a false-negative
    // classification (not connection-level) and made this test flaky (intermittently generating
    // an input the fixture correctly treats as unrecoverable, exiting with SURVIVED never
    // printed, while the test always expected SURVIVED). Every message below independently
    // matches a phrase in CONNECTION_LEVEL_ERROR_MESSAGE_PHRASES regardless of `code`.
    const connectionLevelErrorArb = fc.record({
      message: fc.oneof(
        fc.constant('Connection terminated unexpectedly'),
        fc.constant('Connection terminated'),
        fc.constant('terminated unexpectedly'),
        fc.constant('Client has encountered a connection error')
      ),
      code: fc.option(
        fc.constantFrom('ECONNRESET', 'ECONNREFUSED', 'EPIPE', 'ETIMEDOUT'),
        { nil: undefined }
      ),
    });

    // Non-connection-level: a plain generic error with no recognized code and a message that
    // does not match any of the CONNECTION_LEVEL_ERROR_MESSAGE_PHRASES, so
    // `isConnectionLevelError()` classifies it as false and the guard must still exit(1).
    const nonConnectionLevelError = { message: 'Something totally unexpected went wrong' };

    test('module registers 1 listener each for uncaughtException and unhandledRejection at load time', () => {
      const result = runFixture(UNCAUGHT_UNHANDLED_FIXTURE, {
        CRASH_MODE: 'uncaughtException',
        INJECTED_ERROR: JSON.stringify({ message: 'Connection terminated unexpectedly' }),
      });

      expect(result.stdout).toContain(
        'LISTENER_COUNTS_BEFORE_CRASH=' +
          JSON.stringify({ uncaughtException: 1, unhandledRejection: 1 })
      );
    });

    test(
      'an uncaught exception from a connection-level error no longer crashes the process (guard resets state and survives)',
      () => {
        fc.assert(
          fc.property(connectionLevelErrorArb, (injectedError) => {
            const result = runFixture(UNCAUGHT_UNHANDLED_FIXTURE, {
              CRASH_MODE: 'uncaughtException',
              INJECTED_ERROR: JSON.stringify(injectedError),
            });

            expect(result.status).toBe(0);
            expect(result.stdout).toContain('SURVIVED');
          }),
          { numRuns: 8 }
        );
      },
      20_000
    );

    test(
      'an unhandled promise rejection from a connection-level error no longer crashes the process (guard resets state and survives)',
      () => {
        fc.assert(
          fc.property(connectionLevelErrorArb, (injectedError) => {
            const result = runFixture(UNCAUGHT_UNHANDLED_FIXTURE, {
              CRASH_MODE: 'unhandledRejection',
              INJECTED_ERROR: JSON.stringify(injectedError),
            });

            expect(result.status).toBe(0);
            expect(result.stdout).toContain('SURVIVED');
          }),
          { numRuns: 8 }
        );
      },
      20_000
    );

    test(
      'an uncaught exception from a non-connection-level error still exits the process (does not regress into "never exits")',
      () => {
        const result = runFixture(UNCAUGHT_UNHANDLED_FIXTURE, {
          CRASH_MODE: 'uncaughtException',
          INJECTED_ERROR: JSON.stringify(nonConnectionLevelError),
        });

        expect(result.status).not.toBe(0);
        expect(result.stdout).not.toContain('SURVIVED');
      },
      20_000
    );

    test(
      'an unhandled promise rejection from a non-connection-level error still exits the process (does not regress into "never exits")',
      () => {
        const result = runFixture(UNCAUGHT_UNHANDLED_FIXTURE, {
          CRASH_MODE: 'unhandledRejection',
          INJECTED_ERROR: JSON.stringify(nonConnectionLevelError),
        });

        expect(result.status).not.toBe(0);
        expect(result.stdout).not.toContain('SURVIVED');
      },
      20_000
    );
  });
});
